//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cost_Table
    {
        public int Event_Id { get; set; }
        public int Hotel_Price { get; set; }
        public int Tent_Price { get; set; }
        public int Plate_Price { get; set; }
    }
}
