//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event_Details_Entry
    {
        public int Event_Id { get; set; }
        public int Event_Loc_Id { get; set; }
        public int Tent_Id { get; set; }
        public System.DateTime DOF { get; set; }
        public int Day { get; set; }
        public int Plate_Id { get; set; }
    }
}
