//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Event_ManagementEntities : DbContext
    {
        public Event_ManagementEntities()
            : base("name=Event_ManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Cost_Table> Cost_Table { get; set; }
        public virtual DbSet<Customer_Entry> Customer_Entry { get; set; }
        public virtual DbSet<Event_Details_Entry> Event_Details_Entry { get; set; }
        public virtual DbSet<Event_Table> Event_Table { get; set; }
        public virtual DbSet<Hotel_Event> Hotel_Event { get; set; }
        public virtual DbSet<Plate_Table> Plate_Table { get; set; }
        public virtual DbSet<Tent_Name> Tent_Name { get; set; }
    }
}
