//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plate_Table
    {
        public int Plate_Id { get; set; }
        public string Plate_Name { get; set; }
        public int Price { get; set; }
    }
}
