//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tent_Name
    {
        public int Tent_Id { get; set; }
        public string Tent_Name1 { get; set; }
        public string Tent_Size { get; set; }
        public int Tent_Price { get; set; }
    }
}
